<a href="https://colab.research.google.com/github/DArsem2306/Programa-Python-Utec/blob/main/Tareas/modulo02/Daniel_Arrisueno.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# EVALUACION_MOD2_PROGRAMACION_PYTHON
---



## Daniel Arrisueño

1. Creación de listas (1 puntos)

Crea una lista llamada numeros_pares que contenga los números del 1 al 100 con saltos de 2 en 2.

In [3]:
numeros_pares = list(range(2, 101, 2))
print(numeros_pares)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100]


2. Agregando Numeros

Agrega los números 102, 104 y 106 al final de la lista numeros_pares y luego elimina los primeros 5 números de la lista numeros_pares. Muestra la lista resultante.

In [4]:
# Agregar 102, 104 y 106 al final
numeros_pares.append(102)
numeros_pares.append(104)
numeros_pares.append(106)
# Luego descubri que podria agregarlos con: numeros_pares.extend([102, 104, 106])

# Eliminar los primeros 5 elementos
del numeros_pares[:5]

# Mostrar la lista resultante
print(numeros_pares)

[12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98, 100, 102, 104, 106]


3. Operaciones con listas (2 puntos)

Crea una lista llamada resultante que contenga la raíz cuadrada de cada elemento de la lista numeros_pares usando list comprehension.

In [5]:
import math #debemos importar la libreria

# Creando la lista resultante sobre la raiz cuadrada de numeros_pares
resultante = [round(math.sqrt(num),2) for num in numeros_pares] #Redondeado a 2 numeros para mejor lectura del resultado

print(resultante)

[3.46, 3.74, 4.0, 4.24, 4.47, 4.69, 4.9, 5.1, 5.29, 5.48, 5.66, 5.83, 6.0, 6.16, 6.32, 6.48, 6.63, 6.78, 6.93, 7.07, 7.21, 7.35, 7.48, 7.62, 7.75, 7.87, 8.0, 8.12, 8.25, 8.37, 8.49, 8.6, 8.72, 8.83, 8.94, 9.06, 9.17, 9.27, 9.38, 9.49, 9.59, 9.7, 9.8, 9.9, 10.0, 10.1, 10.2, 10.3]


4. Desempaquetado de tuplas (2 puntos)

Dada la siguiente tupla tupla_x = (“alumno”,”Pedro”,15), desempaqueta la tupla tupla_x en tres variables: x, y, z, e imprime la siguiente estructura “El alumno Pedro obtuvo la calificación de 15 usando las variables x, y, z”.

In [6]:
#Tupla Determinada
tupla_x = ("alumno","Pedro",15)

#Variables en tupla:
x, y, z = tupla_x

# Imprimir el mensaje usando las variables
print(f"El {x} {y} obtuvo la calificación de {z}")

El alumno Pedro obtuvo la calificación de 15


5. Iteración en diccionarios (4 puntos)

Dado el siguiente diccionario notas = {“Programacion”:15.9, “Matematica”: 15.1, “Fisica”:15.6}, escribe un bucle for que imprima cada clave y su valor en el diccionario con la siguiente estructura “Mis calificaciones en el curso de Programacion es 15.9”

In [7]:
#Diccionario de Notas Propuesto
notas = {"Programacion":15.9, "Matematica": 15.1, "Fisica":15.6}

# Bucle pedido para diccionario
for curso, nota in notas.items():
    print(f"Mis calificaciones en el curso de {curso} es {nota}")

Mis calificaciones en el curso de Programacion es 15.9
Mis calificaciones en el curso de Matematica es 15.1
Mis calificaciones en el curso de Fisica es 15.6


6. Matrices y funciones de NumPy (4 puntos)

Crea una matriz 1D que contenga los primeros 16 elementos de la lista numeros_pares (creada en la pregunta 1), modifique las dimensiones y convertiela en una matriz 2D con shape(4,4), calcula la suma total de los elementos de la matriz matriz 2D.

In [16]:
# Importando libreria

import numpy as np

# Armando primera Matriz con los primeros 16 elementos
matriz_1D = np.array(numeros_pares[:16])

# Convertir matriz 1D en 2D con shape (4, 4)
matriz_2D = matriz_1D.reshape((4, 4))

# Calculando la suma total de los elementos M2D
suma_total = matriz_2D.sum()

# Mostrar resultados
print("Matriz 1D:\n ")
print(matriz_1D)
print("\n=========")
print("\nMatriz 2D:\n")
print(matriz_2D)
print(f"\nSuma total de elementos: {suma_total}")

Matriz 1D:
 
[12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42]


Matriz 2D:

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]
 [36 38 40 42]]

Suma total de elementos: 432


7. Pandas (6 puntos)

Leer el archivo datosDemograficos.xlsx y realice un análisis descriptivo en función de las variables más relevantes.

In [17]:
# Importando libreria

import pandas as pd

# Leer el archivo Excel
df = pd.read_excel("datosDemograficos.xlsx")

# Mostrar las primeras filas
df.head()

Indicadores  Fecundidad  Mortalidad  TasaMortalidadxMil  EsperanzaVida  \
0        Puno       30108        9951                6.86          71.44   
1  San Martín       16074        4889                5.63          72.45   
2       Tacna        5605        1900                5.40          75.11   
3      Tumbes        3924        1209                4.94          74.96   
4     Ucayali        8872        3020                5.93          71.99   

   EVSoloHombres  EVSoloMujeres  TasaMortalidadInfantilxMilNacidos  \
0          68.77          74.25                              26.82   
1          69.65          75.40                              17.53   
2          72.31          78.06                              11.77   
3          72.09          77.98                              11.46   
4          69.24          74.87                              21.07   

   CrecimientoNatural  
0               20157  
1               11185  
2                3705  
3                2715  
4                5852

In [19]:
#Revisando columnas disponibles
print(df.columns)

Index(['Indicadores', 'Fecundidad', 'Mortalidad', 'TasaMortalidadxMil',
       'EsperanzaVida', 'EVSoloHombres', 'EVSoloMujeres',
       'TasaMortalidadInfantilxMilNacidos', 'CrecimientoNatural'],
      dtype='object')


In [21]:
#Revisando información general del dataset:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 9 columns):
 #   Column                             Non-Null Count  Dtype  
---  ------                             --------------  -----  
 0   Indicadores                        25 non-null     object 
 1   Fecundidad                         25 non-null     int64  
 2   Mortalidad                         25 non-null     int64  
 3   TasaMortalidadxMil                 24 non-null     float64
 4   EsperanzaVida                      25 non-null     float64
 5   EVSoloHombres                      25 non-null     float64
 6   EVSoloMujeres                      25 non-null     float64
 7   TasaMortalidadInfantilxMilNacidos  25 non-null     float64
 8   CrecimientoNatural                 25 non-null     int64  
dtypes: float64(5), int64(3), object(1)
memory usage: 1.9+ KB


In [20]:
# Estadísticas básicas solo de columnas numéricas
df.describe()

Fecundidad   Mortalidad  TasaMortalidadxMil  EsperanzaVida  \
count      25.000000     25.00000           24.000000      25.000000   
mean    22874.400000   7265.28000            5.711667      74.059600   
std     30817.223005  10451.42713            0.580777       2.375038   
min      2571.000000    660.00000            4.540000      70.930000   
25%      8872.000000   2788.00000            5.397500      71.990000   
50%     16074.000000   5234.00000            5.545000      73.290000   
75%     24385.000000   8450.00000            5.985000      76.450000   
max    163089.000000  55201.00000            6.970000      78.380000   

       EVSoloHombres  EVSoloMujeres  TasaMortalidadInfantilxMilNacidos  \
count      25.000000      25.000000                          25.000000   
mean       71.337200      76.919200                          16.984000   
std         2.315498       2.443766                           5.434434   
min        68.530000      73.450000                           7.810000   
25%        69.240000      74.870000                          11.770000   
50%        70.710000      76.000000                          16.890000   
75%        73.650000      79.390000                          20.000000   
max        75.680000      81.220000                          26.820000   

       CrecimientoNatural  
count           25.000000  
mean         15609.120000  
std          20409.736145  
min           1566.000000  
25%           5852.000000  
50%          11452.000000  
75%          16320.000000  
max         107888.000000

In [22]:
# Distribución de variables numéricas
df.describe()

# Valores únicos o rangos
print("Valores únicos por columna:")
print(df.nunique())

Valores únicos por columna:
Indicadores                          25
Fecundidad                           25
Mortalidad                           25
TasaMortalidadxMil                   21
EsperanzaVida                        25
EVSoloHombres                        25
EVSoloMujeres                        25
TasaMortalidadInfantilxMilNacidos    23
CrecimientoNatural                   25
dtype: int64
